import Vue from "vue";
import { Tab, Tabs } from 'vant';
import { Cascader, Popup, Field } from 'vant';
import { Button } from 'vant';
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Button);
Vue.use(Cascader);
Vue.use(Popup);
Vue.use(Field);
